sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: l+bxhlJAvU85dTDt0dCI89fSfHWruN23VMJiqyLc5B/s7ZrlL5mIQIewHOAvHN4spnFMUwXrz1NdU2E9xaan4CIhnnoUkDNZnj+7dkpHcwmBZl+5YZmGBCkU63uR4psycWuk1+W0++X3Otsjn3FQattA6KezQw7mLS5x5oETETBAIJUqkiuihU1umQVdK0cnrVBJjDXKbQaq5CjBuydvOnGJ1ePTgzznfk+lWAz81RmR4aPuQjr7AzrSun3il6xpYJt9dBd2DwLl19gWJazawgHlQQ1b4X+uRjNf7qcWH1CJecudbu68Yq28UgQsuyn2jhEocJL64kGWT5Do5Kw5Br0gTwiSGYLGeCvG9s0+NzCMV+GcbkKkIahcqzFTzQD9sVe3ismv/jYOZINQksvwinMduyhaoSOiznHePspkqIorrk+M9tLQsQGPVJdOZY0608eq/qR3P3DRcxR67t1/QA4oHSrxXS6r/861XgDvThpSEwXg/aazQvq+z4yCp0hdUo9BMJvR3s2fHhfzYWxruB5UCqa3rrYo5D9RKqxSpYLk/XffD+PBMX6J7JlhBfjEoFcrsmBVv4E9o4uYgtP54nql80ZUhkAIg8HT3h2mycm/ptBjA3GKY9dw5vswKsEG+JvQIhHlRzxY9Y6pdAKxXjCFCal+ZiCHTgGwjlFpg/s=
  - secure: lXJUPqTMhRPhD68xOdnqol6mxobBjBZiHAeWUZuZCfN+1n2bfcYkPvAKfs4d/Xs0bdGticRPaS3a9bxzrblWGk8rpQwwSzzQflAxVg1IzHXMxEM0R1fH9TpkAiwszlfd6LcCPow9kC6Q8c/s39YnTVhWvHVA9c9WGGqh2TR8Mh999BNV35IPhEw5EGwIoAkihasMpXzvfvU305h33gJikICJE+d3sPD3IrXJCZipNVQt3mV34EiqEfwxHDPBWfS1hpnxfgb0Brj8gMB0laGouwhPYr0Y1xmmywfh4SBsrxj6MtB+s6A9lgiMCwrROpj+zfBwVl2dktbchcpbbAcnneJi/vxKtrHFtoq/aPwQLhD7hHG7JXut/nUoSLxDtMo1tGdk3XjbZioq4gIkh0AV0MlAkb4fD4fWLpA1PQi/HOBflUEw6oMHsh+Ei/NkQEastvnI29pu5cpac5ls1fnU2raiu98dThPyNhwS/QOxWXFd2buzydYw4Cxne9ls3u53s+WF0SJvLFcEHJYXFsHjLxweA2uNpx8vwmSdJ2koHZBWdneRdu0LeoEd4fbkOnQO2zNI3EYuLXEs3mcTYzTjPbBf128Z7nmZzad8PBdDe/CAL/nQojD7Q+uWcAZ07l89iYaa6kAR0ySfop0vXVojUyUGaqEqThWxT+sY4ldpzjM=
